# Generated by Django 6.0.3 on 2026-04-02 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_token',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_token_expires',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
