# Generated by Django 6.0.3 on 2026-04-02 21:50

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0002_profile_reset_token_profile_reset_token_expires'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='country',
            field=django_countries.fields.CountryField(blank=True, help_text='Pays de résidence', max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Numéro de téléphone', max_length=20, null=True),
        ),
    ]
