# Generated by Django 5.2.13 on 2026-04-09 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0003_profile_country_profile_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Titre du document', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Description courte du document')),
                ('file', models.FileField(help_text='Fichier PDF à télécharger', upload_to='documents/pdfs/')),
                ('is_active', models.BooleanField(default=True, help_text='Document visible par les utilisateurs')),
                ('require_vip', models.BooleanField(default=False, help_text='Réservé aux utilisateurs VIP uniquement')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Document PDF',
                'verbose_name_plural': 'Documents PDF',
                'ordering': ['-date_created'],
            },
        ),
    ]
