# Generated by Django 5.2.13 on 2026-04-10 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0004_pdfdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='matricule_counter',
            field=models.PositiveIntegerField(default=10000, help_text='Compteur de départ pour la génération des matricules. Le prochain matricule sera PRÉFIXE + ce numéro.'),
        ),
        migrations.AddField(
            model_name='globalsettings',
            name='matricule_prefix',
            field=models.CharField(default='GZG', help_text='Préfixe du matricule utilisateur (ex: AEWR, GZG). Les numéros seront générés automatiquement.', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='matricule',
            field=models.CharField(blank=True, help_text='Matricule unique généré automatiquement (ex: GZG10001)', max_length=50, null=True, unique=True),
        ),
    ]
