# Generated by Django 5.2.13 on 2026-04-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0005_globalsettings_matricule_counter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('play_store_url', models.URLField(default='https://play.google.com/store/apps', help_text="Lien de l'application sur le Play Store", max_length=500)),
                ('is_active', models.BooleanField(default=True, help_text="Afficher la page de téléchargement après l'inscription")),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': "Lien de l'Application",
                'verbose_name_plural': "Lien de l'Application",
            },
        ),
    ]
