# Generated by Django 5.2.13 on 2026-04-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parrainage', '0006_applink'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalsettings',
            name='referral_limit',
            field=models.PositiveIntegerField(default=2, help_text='Nombre maximum de filleuls directs par utilisateur (défaut: 2)'),
        ),
    ]
